ydata: use other-transcode

diff --git a/app/ydata b/app/ydata
--- a/app/ydata
+++ b/app/ydata
@@ -17,7 +17,7 @@ export \
 
 # shellcheck disable=SC2034 # Variable appears unused.
 readonly \
-	BASE_APP_VERSION=0.9.20230403 \
+	BASE_APP_VERSION=0.9.20230427 \
 	BASE_MIN_VERSION=0.9.20230315
 
 # shellcheck disable=SC1091 # File not following.
@@ -66,18 +66,17 @@ check() {
 	fi
 }
 
-# Converts to general formats.
+# Converts to general formats. If other-transcode fails doesn't die.
 convert() {
-	isempty "$VID" ||
+	if ! isempty "$VID"; then
+		cd "$RES" || die Unable to change direcory to "$RES".
 		{
-			transcode \
-				--act \
-				--dir "$VID" \
-				--out "$RES" \
-				--wid "$WID" \
-				2>&1 1>&3 3>&- | tologe
+			other-transcode "$VID"/* || : 2>&1 1>&3 3>&- | tologe
 		} \
 			3>&1 1>&2 | tolog
+		rm -f ./*.log
+		cd - || die Unable to change directory back.
+	fi
 	isempty "$AUD" ||
 		{
 			transcode \
@@ -172,6 +171,7 @@ validate() {
 	validate_cmd \
 		HandBrakeCLI \
 		mp4track \
+		other-transcode \
 		renamr \
 		rsync \
 		tput \
